name = "kermit-website-thumbnail-generator"
main = "src/index.ts"
compatibility_date = "2024-02-23"
compatibility_flags = [ "nodejs_compat"]

# Browser Rendering API binding
browser = { binding = "MYBROWSER" }

# Bind an R2 Bucket
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "kermit-website-thumbnail-generator-screenshots"
preview_bucket_name = "kermit-website-thumbnail-generator-screenshots-test"

# Binding to a Durable Object
[[durable_objects.bindings]]
name = "BROWSER"
class_name = "Browser"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Browser"] # Array of new classes